[tools]
go = "1.23.12"
jq = "1.8.1"
python = "3.13.7"
node = "24.7.0"
golangci-lint = "1.61.0"
rg = "latest"
java = "25.0.0"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
rust = "latest"
yazi = "latest"
ffmpeg = "latest"
zoxide = "latest"
resvg = "latest"
