---
configure_dotfiles: false
configure_terminal: true
configure_osx: false
configure_dock: false
configure_sudoers: false
configure_sublime: false

homebrew_taps:
  - anomalyco/tap
  - y3owk1n/tap

  # TODO: Revisit
  # - FelixKratz/formulae
  # - koekeishiya/formulae

homebrew_installed_packages:
  # Privacy
  - ykman

  # Development
  - chezmoi
  - neovim
  - tmux
  - anomalyco/tap/opencode
  - claude-code

  # LazyVim
  - lazygit
  - tree-sitter-cli
  - fzf
  - ripgrep
  - fd

  # Version Manager
  - mise

  # Python Build Deps
  - openssl
  - readline
  - sqlite3
  - xz
  - zlib
  - tcl-tk@8
  - libb2

  # Golang Build Deps
  - mercurial
  - bison

  # Containers
  - colima
  - docker
  - docker-compose

  # Utility
  - mole
  - zoxide

  # TODO: Revisit
  # - borders
  # - skhd

homebrew_cask_apps:
  - font-jetbrains-mono-nerd-font

  # Privacy
  - keepassxc
  - gpg-suite
  - little-snitch
  - cryptomator
  - veracrypt

  # Productivity
  - obsidian
  - libreoffice

  # Browsers
  - browserosaurus
  - brave-browser
  - librewolf
  - firefox
  - orion
  - mullvad-browser

  # Utility
  - raycast
  - aldente
  - lunar
  - cleanshot

  # Navigation
  - nikitabobko/tap/aerospace
  - y3owk1n/tap/neru

  # Development
  - ghostty
  - jetbrains-toolbox
  - goland
  - visual-studio-code
  - android-studio

  # Work
  - google-chrome
  - gcloud-cli
  - postman
  - dbeaver-community

homebrew_cask_appdir: /Applications

mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1085114709, name: "Parallels Desktop" }
  - { id: 803453959, name: "Slack for Desktop" }
  - { id: 747648890, name: "Telegram" }
  - { id: 1661733229, name: "LocalSend" }
  - { id: 1497506650, name: "Yubico Authenticator" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 6720708363, name: "Obsidian Web Clipper" }
  - { id: 966085870, name: "TickTick" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1452453066, name: "Hidden Bar" }

mas_email: ""
mas_password: ""

post_provision_tasks: []
