---
configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_dock: false
configure_sudoers: false
configure_sublime: false

homebrew_taps: []
homebrew_installed_packages: []
homebrew_cask_apps: []
homebrew_cask_appdir: /Applications

mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1085114709, name: "Parallels Desktop" }
  - { id: 803453959, name: "Slack for Desktop" }
  - { id: 747648890, name: "Telegram" }
  - { id: 1661733229, name: "LocalSend" }
  - { id: 1497506650, name: "Yubico Authenticator" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 6720708363, name: "Obsidian Web Clipper" }
  - { id: 966085870, name: "TickTick" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1452453066, name: "Hidden Bar" }

mas_email: ""
mas_password: ""

post_provision_tasks: []
