# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md#configuration
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false
control_server_enable = false

[defaults]
kanata_executable = '~/.local/bin/kanata-tray-kanata'
tcp_port = 5829
autorestart_on_crash = false

[presets.'Main']
kanata_config = '~/.config/kanata/kanata.kbd'
autorun = true
