
# --- General Settings ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g set-clipboard on

# --- Status Bar ---
set -g status-position top
set -g status-style "bg=#1c1c1c,fg=#808080"
set -g status-left "#[bg=#333333,fg=#e0e0e0,bold] #S #[default] "
set -g status-right "#[bg=#333333,fg=#e0e0e0] %H:%M #[default]"
set -g status-left-length 30
set -g window-status-current-format "#[bg=#333333,fg=#ffffff,bold] #I:#W "
set -g window-status-format " #I:#W "

# --- Pane Borders ---
set -g pane-border-style "fg=#333333"
set -g pane-active-border-style "fg=#e0e0e0"

# --- Tmux Plugin Manager ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
